export const CLEAR_STATE = 'CLEAR_STATE';

export const START_KERNEL_FETCH = 'START_KERNEL_FETCH';
export const START_KERNEL_SUCCESS = 'START_KERNEL_SUCCESS';
export const START_KERNEL_ERROR = 'START_KERNEL_ERROR';

export const INTERRUPT_KERNEL_FETCH = 'INTERRUPT_KERNEL_FETCH';
export const INTERRUPT_KERNEL_SUCCESS = 'INTERRUPT_KERNEL_SUCCESS';
export const INTERRUPT_KERNEL_ERROR = 'INTERRUPT_KERNEL_ERROR';

export const RESTART_KERNEL_FETCH = 'RESTART_KERNEL_FETCH';
export const RESTART_KERNEL_SUCCESS = 'RESTART_KERNEL_SUCCESS';
export const RESTART_KERNEL_ERROR = 'RESTART_KERNEL_ERROR';

export const KILL_KERNEL_FETCH = 'KILL_KERNEL_FETCH';
export const KILL_KERNEL_SUCCESS = 'KILL_KERNEL_SUCCESS';
export const KILL_KERNEL_ERROR = 'KILL_KERNEL_ERROR';

export const UPDATE_KERNEL_STATUS = 'UPDATE_KERNEL_STATUS';
