// Filter Pattern actions types
export const ADD_FILTER_TO_PATH = 'ADD_FILTER_TO_PATH';
export const UPDATE_FILTERS_ON_PATH = 'UPDATE_FILTERS_ON_PATH';
export const REMOVE_FILTER_FROM_PATH = 'REMOVE_FILTER_FROM_PATH';
export const REORDER_FILTER_ON_PATH = 'REORDER_FILTER_ON_PATH';
export const REORDER_SELECTED_FILTERS_ON_PATH =
  'REORDER_SELECTED_FILTERS_ON_PATH';
export const DELETE_ALL_FILTERS_ON_PATH = 'DELETE_ALL_FILTERS_ON_PATH';
export const CLEAR_ALL_FILTERS_ON_PATH = 'CLEAR_ALL_FILTERS_ON_PATH';
export const TOGGLE_EDIT_GROUP_TITLE_MODE = 'TOGGLE_EDIT_GROUP_TITLE_MODE';
export const UPDATE_TEMP_GROUP_TITLE = 'UPDATE_TEMP_GROUP_TITLE';
export const UPDATE_GROUP_TITLE = 'UPDATE_GROUP_TITLE';
export const UPDATE_DRAGGED_FILTER_ID = 'UPDATE_DRAGGED_FILTER_ID';
export const APPLY_SAVED_PATTERN = 'APPLY_SAVED_PATTERN';
export const APPLY_SAVED_PATTERN_TO_GROUP = 'APPLY_SAVED_PATTERN_TO_GROUP';

export const MOVE_FILTER_TO_GROUP = 'MOVE_FILTER_TO_GROUP';
export const MOVE_SELECTED_FILTERS_TO_GROUP = 'MOVE_SELECTED_FILTERS_TO_GROUP';
export const MOVE_FILTER_FROM_GROUP_TO_PATH = 'MOVE_FILTER_FROM_GROUP_TO_PATH';
export const MOVE_FILTER_WITHIN_GROUP = 'MOVE_FILTER_WITHIN_GROUP';
// Filter Library actions
export const POPULATE_FILTER_LIBRARY = 'POPULATE_FILTER_LIBRARY';
export const POPULATE_FILTER_LIBRARY_RAW = 'POPULATE_FILTER_LIBRARY_RAW';
export const TOGGLE_FILTER_LIBRARY_HINT = 'TOGGLE_FILTER_LIBRARY_HINT';
export const TOGGLE_FILTER_LIBRARY_DESCRIPTION =
  'TOGGLE_FILTER_LIBRARY_DESCRIPTION';
export const SEARCH_LIBRARY = 'SEARCH_LIBRARY';
export const ADD_FILTER_BY_CRITERIA = 'ADD_FILTER_BY_CRITERIA';
export const UPDATE_FILTER_BY_CRITERIA = 'UPDATE_FILTER_BY_CRITERIA';
export const REMOVE_ALL_FILTER_BY_CRITERIA = 'REMOVE_ALL_FILTER_BY_CRITERIA';

// Filter actions
export const ADD_FILTER_PARAMETER = 'ADD_FILTER_PARAMETER';
export const FILTER_SELECTION = 'FILTER_SELECTION';
export const TOGGLE_FILTER_SELECTION = 'TOGGLE_FILTER_SELECTION';
export const TOGGLE_FILTER_SELECTION_PREVENTED =
  'TOGGLE_FILTER_SELECTION_PREVENTED';
export const BULK_TOGGLE_FILTER_SELECTION = 'BULK_TOGGLE_FILTER_SELECTION';

export const GROUP_SELECTED_FILTERS = 'GROUP_SELECTED_FILTERS';
export const UNGROUP_SELECTED_FILTERS = 'UNGROUP_SELECTED_FILTERS';

export const TOGGLE_FILTER_PARAM_DROPDOWN = 'TOGGLE_FILTER_PARAM_DROPDOWN';
export const FILTER_FILTER_PARAM_DROPDOWN = 'FILTER_FILTER_PARAM_DROPDOWN';

export const CHANGE_FILTER_CONNECTOR = 'CHANGE_FILTER_CONNECTOR';
export const TOGGLE_FILTER_OPENED = 'TOGGLE_FILTER_OPENED';
export const OPEN_FILTER = 'OPEN_FILTER';
export const CLOSE_FILTER = 'CLOSE_FILTER';

export const CLEAR_EMPTY_DELETED_GROUPS = 'CLEAR_EMPTY_DELETED_GROUPS';
export const FILTER_DRAG_STARTED = 'FILTER_DRAG_STARTED';
export const FILTER_DRAG_ENDED = 'FILTER_DRAG_ENDED';

// Filter parameter actions
export const CHANGE_PARAM_OPERATOR = 'CHANGE_PARAM_OPERATOR';
export const CHANGE_PARAM_VALUE = 'CHANGE_PARAM_VALUE';
export const CHANGE_PARAM_CONNECTOR = 'CHANGE_PARAM_CONNECTOR';
export const REMOVE_FILTER_PARAMETER = 'REMOVE_FILTER_PARAMETER';

// Layout actions
export const TOGGLE_FILTER_PATH = 'TOGGLE_FILTER_PATH';
export const TOGGLE_LIBRARY = 'TOGGLE_LIBRARY';
export const TOGGLE_SAVED = 'TOGGLE_SAVED';
export const TOGGLE_EMPTY_GROUP_DELETED_OPEN_MODAL =
  'TOGGLE_EMPTY_GROUP_DELETED_OPEN_MODAL';
export const TOGGLE_LOAD_PATTERN_OPEN_MODAL = 'TOGGLE_LOAD_PATTERN_OPEN_MODAL';
export const TOGGLE_SCROLL_EFFECT = 'TOGGLE_SCROLL_EFFECT';
export const SET_SPLIT_POSITION = 'SET_SPLIT_POSITION';
export const SET_SERVER_ERROR = 'SET_SERVER_ERROR';
export const CLEAR_SERVER_ERROR = 'CLEAR_SERVER_ERROR';
export const DISPLAY_TOAST = 'DISPLAY_TOAST';
export const CLEAR_TOAST_OPEN = 'CLEAR_TOAST_OPEN';
export const SET_DOCUMENT_ID = 'SET_DOCUMENT_ID';

// Filter Menu actions
export const OPEN_PATH_DROPDOWN_MENU = 'OPEN_PATH_DROPDOWN_MENU';
export const CLOSE_PATH_DROPDOWN_MENU = 'CLOSE_PATH_DROPDOWN_MENU';

// Result Stage actions
export const POPULATE_RESULTS_COUNT = 'POPULATE_RESULTS_COUNT';
export const SET_SETTING_VISIBLE = 'SET_SETTING_VISIBLE';
export const CLEAR_RESULT_STAGE_SETTING = 'CLEAR_RESULT_STAGE_SETTING';
export const SET_SELECTED_COLUMNS = 'SET_SELECTED_COLUMNS';
export const POPULATE_CYPHER = 'POPULATE_CYPHER';
export const POPULATE_TABLE_COLUMNS = 'POPULATE_TABLE_COLUMNS';
export const SET_FIRST_LOAD = 'SET_FIRST_LOAD';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const SET_TIMESTAMP_VALUES = 'SET_TIMESTAMP_VALUES';

// Column Builder
export const UPDATE_COLUMN_BUILDER_SEARCH = 'UPDATE_COLUMN_BUILDER_SEARCH';
export const RESET_COLUMN_BUILDER_SEARCH = 'RESET_COLUMN_BUILDER_SEARCH';
export const BUILD_COLUMN_BUILDER_DEFAULT = 'BUILD_COLUMN_BUILDER_DEFAULT';
export const MAKE_COLUMN_BUILDER_DEFAULT_SELECTION =
  'MAKE_COLUMN_BUILDER_DEFAULT_SELECTION';
export const CHANGE_COLUMN_BUILDER_DROP_STATE =
  'CHANGE_COLUMN_BUILDER_DROP_STATE';
export const TOGGLE_COLUMN_BUILDER_SECTION_COLLAPSED_STATE =
  'TOGGLE_COLUMN_BUILDER_SECTION_COLLAPSED_STATE';

export const UPDATE_GROUP_BY_SEARCH = 'UPDATE_GROUP_BY_SEARCH';
export const RESET_GROUP_BY_SEARCH = 'RESET_GROUP_BY_SEARCH';
export const CHANGE_GROUP_BY_DROP_STATE = 'CHANGE_GROUP_BY_DROP_STATE';
export const BUILD_GROUP_BY_DEFAULT = 'BUILD_GROUP_BY_DEFAULT';
// Quip actions
export const QUIP_APP_ACTIVE = 'QUIP_APP_ACTIVE';
export const QUIP_APP_FULLSCREEN = 'QUIP_APP_FULLSCREEN';

// Load Path actions
export const UPDATE_LOAD_PATH_MODAL = 'UPDATE_LOAD_PATH_MODAL';

// Saved patterns actions
export const UPDATE_SAVED_PATTERNS_DATA = 'UPDATE_SAVED_PATTERNS_DATA';
export const TOGGLE_SAVED_PATTERNS_HINT = 'TOGGLE_SAVED_PATTERNS_HINT';
export const TOGGLE_SAVED_PATTERNS_DESCRIPTION =
  'TOGGLE_SAVED_PATTERNS_DESCRIPTION';
export const UPDATE_SAVE_PATTERN_NAME = 'UPDATE_SAVE_PATTERN_NAME';
export const UPDATE_SAVE_PATTERN_DESCRIPTION =
  'UPDATE_SAVE_PATTERN_DESCRIPTION';
export const UPDATE_SAVED_PATTERN_NAME_AVAILABLE =
  'UPDATE_SAVED_PATTERN_NAME_AVAILABLE';
export const SAVED_PATTERN_REQUEST_PENDING = 'SAVED_PATTERN_REQUEST_PENDING';
export const SAVED_PATTERN_REQUEST_SUCCESS = 'SAVED_PATTERN_REQUEST_SUCCESS';
export const SAVED_PATTERN_REQUEST_FAILED = 'SAVED_PATTERN_REQUEST_FAILED';
export const SAVED_PATTERN_SEARCH_TERM = 'SAVED_PATTERN_SEARCH_TERM';

//Jupyter actions
export const FETCH_VARIABLE_NAME_PENDING = 'FETCH_VARIABLE_NAME_PENDING';
export const FETCH_VARIABLE_NAME_SUCCESS = 'FETCH_VARIABLE_NAME_SUCCESS';
export const FETCH_VARIABLE_NAME_FAILURE = 'FETCH_VARIABLE_NAME_FAILURE';
export const VALIDATE_VARIABLE_NAME = 'VALIDATE_VARIABLE_NAME';
export const SET_VARIABLE_NAME_PENDING = 'SET_VARIABLE_NAME_PENDING';
export const SET_VARIABLE_NAME_SUCCESS = 'SET_VARIABLE_NAME_SUCCESS';
export const SET_VARIABLE_NAME_FAILURE = 'SET_VARIABLE_NAME_FAILURE';
export const FETCH_KERNEL_STATUS_PENDING = 'FETCH_KERNEL_STATUS_PENDING';
export const FETCH_KERNEL_STATUS_SUCCESS = 'FETCH_KERNEL_STATUS_SUCCESS';
export const FETCH_KERNEL_STATUS_FAILURE = 'FETCH_KERNEL_STATUS_FAILURE';
export const EXPORT_SPREADSHEET_PENDING = 'EXPORT_SPREADSHEET_PENDING';
export const EXPORT_SPREADSHEET_SUCCESS = 'EXPORT_SPREADSHEET_SUCCESS';
export const EXPORT_SPREADSHEET_FAILURE = 'EXPORT_SPREADSHEET_FAILURE';
export const DOWNLOAD_CSV_PENDING = 'DOWNLOAD_CSV_PENDING';
export const DOWNLOAD_CSV_SUCCESS = 'DOWNLOAD_CSV_SUCCESS';
export const DOWNLOAD_CSV_FAILURE = 'DOWNLOAD_CSV_FAILURE';
